### ISSUE TITLE
默认加载一直在转，不能拉取消息

### ISSUE THREAD

**Issue by xybin1990** [fanjyy/lemon-imui#6]
当没有消息或消息数量很少的时候，直接触发了on-reach的方法拉取消息，不能向上滚动触发更新了，优化一下？
<img width="882" alt="image" src="https://user-images.githubusercontent.com/9530270/91381718-a3bd1500-e85a-11ea-8126-4f827144029f.png">

**Comment by fanjyy** [comment]
在pull-messages 事件里调用 next(messages,true);  第二个参数表示是否无更多消息

**Comment by xybin1990** [comment]
> 在pull-messages 事件里调用 next(messages,true); 第二个参数表示是否无更多消息

嗯，谢谢
